
# parser_WikiDataParser_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb2R\x84\x0b,\x1ct}\xaa\xb0\xe7\xad\x8c\x01S\xa7'
    
_lr_action_items = {'BEGIN':([0,9,],[1,1,]),'END':([3,5,7,8,10,11,12,],[-2,8,-2,-1,-3,-5,-4,]),'EQUALS':([6,],[9,]),'VALUE':([1,4,9,],[3,6,12,]),'PIPE':([3,7,8,11,12,],[4,4,-1,-5,-4,]),'$end':([2,8,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements_list':([3,7,],[5,10,]),'description':([0,9,],[2,11,]),'statement':([4,],[7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> description","S'",1,None,None,None),
  ('description -> BEGIN VALUE statements_list END','description',4,'p_description','parser.py',51),
  ('statements_list -> <empty>','statements_list',0,'p_statement_list_empty','parser.py',55),
  ('statements_list -> PIPE statement statements_list','statements_list',3,'p_statement_list','parser.py',59),
  ('statement -> VALUE EQUALS VALUE','statement',3,'p_statement','parser.py',65),
  ('statement -> VALUE EQUALS description','statement',3,'p_statement','parser.py',66),
]
